{
 "title": "Heizungs- & PV-Entscheidungsdashboard",
 "time": { "from": "now", "to": "now+48h" },
 "templating": {
  "list": [
   {
    "name": "anlage_id",
    "label": "Anlage",
    "query": "select installation_id from system_snapshot  group by installation_id"
   },
   { "name": "s_decision", "label": "Alternative Aktionen", "query": "EIN, AUS" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 7, "x": 0, "y": 0 },
   "options": {
    "content": "# Mögliche Aktion \n#### innerhalb des Prognosezeitraums\n"
   }
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 9, "x": 7, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "WITH cfg AS (\n    SELECT\n        MAX(CASE WHEN key='solar_threshold' THEN CAST(value AS REAL) END) AS solar_threshold,\n        MAX(CASE WHEN key='min_solar_buffer_threshold' THEN CAST(value AS REAL) END) AS min_buffer,\n        MAX(CASE WHEN key='solar_buffer_threshold' THEN CAST(value AS REAL) END) AS max_buffer\n    FROM meta_config\n),\nbuf AS (\n    SELECT buffer_temp\n    FROM system_snapshot\n    ORDER BY timestamp_mez DESC\n    LIMIT 1\n)\n\nSELECT \n    strftime('%F %H:00:00', d.timestamp),\n\n    CASE\n        WHEN d.radiation > cfg.solar_threshold\n         AND buf.buffer_temp BETWEEN cfg.min_buffer AND cfg.max_buffer\n        THEN 'WAIT_SOLAR'\n        ELSE d.action\n    END AS decision\n\nFROM decision_logic d\nCROSS JOIN cfg\nCROSS JOIN buf\n\nWHERE strftime('%F %H:00:00','now','localtime','+1 hour')\n      = strftime('%F %H:00:00', d.timestamp);",
     "rawQueryText": "WITH cfg AS (\n    SELECT\n        MAX(CASE WHEN key='solar_threshold' THEN CAST(value AS REAL) END) AS solar_threshold,\n        MAX(CASE WHEN key='min_solar_buffer_threshold' THEN CAST(value AS REAL) END) AS min_buffer,\n        MAX(CASE WHEN key='solar_buffer_threshold' THEN CAST(value AS REAL) END) AS max_buffer\n    FROM meta_config\n),\nbuf AS (\n    SELECT buffer_temp\n    FROM system_snapshot\n    ORDER BY timestamp_mez DESC\n    LIMIT 1\n)\n\nSELECT \n    strftime('%F %H:00:00', d.timestamp),\n\n    CASE\n        WHEN d.radiation > cfg.solar_threshold\n         AND buf.buffer_temp BETWEEN cfg.min_buffer AND cfg.max_buffer\n        THEN 'WAIT_SOLAR'\n        ELSE d.action\n    END AS decision\n\nFROM decision_logic d\nCROSS JOIN cfg\nCROSS JOIN buf\n\nWHERE strftime('%F %H:00:00','now','localtime','+1 hour')\n      = strftime('%F %H:00:00', d.timestamp);",
     "rawSql": "SELECT action FROM decision_logic ORDER BY timestamp DESC LIMIT 1;",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 17, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT\n 'Wohnort' as text,\n temp_now\n from weather_forecast\n where datetime('now', 'localtime', '+1 hour') >= datetime(timestamp)\n order by timestamp desc\n Limit 1\n \n\n ",
     "rawQueryText": "SELECT\n 'Wohnort' as text,\n temp_now\n from weather_forecast\n where datetime('now', 'localtime', '+1 hour') >= datetime(timestamp)\n order by timestamp desc\n Limit 1\n \n\n ",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT\nstrftime('%d.%m.%Y', 'now', 'localtime') as Datum,\nstrftime('%R','now','localtime') AS Zeit",
     "rawQueryText": "SELECT\nstrftime('%d.%m.%Y', 'now', 'localtime') as Datum,\nstrftime('%R','now','localtime') AS Zeit",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 9, "x": 7, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "WITH current_action AS (\n    SELECT action\n    FROM decision_logic\n    WHERE datetime(timestamp) >= datetime('now','localtime')\n    ORDER BY datetime(timestamp)\n    LIMIT 1\n)\nSELECT \n'neue mögliche Aktion voraussichtlich am   '|| strftime('%d.%m.%Y', datetime(timestamp), '-1 hour') || ' nach ' || strftime(' %H:%M', datetime(timestamp), '-1 hour') || ' Uhr'\nFROM decision_logic\nWHERE datetime(timestamp) > datetime('now','localtime')\n  AND action <> (SELECT action FROM current_action)\nORDER BY datetime(timestamp)\nLIMIT 1",
     "rawQueryText": "WITH current_action AS (\n    SELECT action\n    FROM decision_logic\n    WHERE datetime(timestamp) >= datetime('now','localtime')\n    ORDER BY datetime(timestamp)\n    LIMIT 1\n)\nSELECT \n'neue mögliche Aktion voraussichtlich am   '|| strftime('%d.%m.%Y', datetime(timestamp), '-1 hour') || ' nach ' || strftime(' %H:%M', datetime(timestamp), '-1 hour') || ' Uhr'\nFROM decision_logic\nWHERE datetime(timestamp) > datetime('now','localtime')\n  AND action <> (SELECT action FROM current_action)\nORDER BY datetime(timestamp)\nLIMIT 1",
     "rawSql": "SELECT action FROM decision_logic ORDER BY timestamp DESC LIMIT 1;",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Mögliche Maßnahmen (Wirkung von links nach rechts abnehmend)",
   "type": "table",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {
     "queryText": "WITH cfg AS (\n    SELECT\n        MAX(CASE WHEN key='solar_threshold' THEN CAST(value AS REAL) END) AS solar_threshold,\n        MAX(CASE WHEN key='min_solar_buffer_threshold' THEN CAST(value AS REAL) END) AS min_buffer,\n        MAX(CASE WHEN key='solar_buffer_threshold' THEN CAST(value AS REAL) END) AS max_buffer\n    FROM meta_config\n),\nbuf AS (\n    SELECT buffer_temp\n    FROM system_snapshot\n    ORDER BY timestamp_mez DESC\n    LIMIT 1\n),\nsolar AS (\n    SELECT\n        CASE\n            WHEN d.radiation > cfg.solar_threshold\n             AND buf.buffer_temp BETWEEN cfg.min_buffer AND cfg.max_buffer\n            THEN 1 ELSE 0\n        END AS solar_active\n    FROM decision_logic d\n    CROSS JOIN cfg\n    CROSS JOIN buf\n    WHERE strftime('%F %H:00:00', 'now', 'localtime', '+1 hour')\n          = strftime('%F %H:00:00', d.timestamp)\n    LIMIT 1\n),\ndecision AS (\n    SELECT action\n    FROM decision_logic\n    WHERE strftime('%F %H:00:00', 'now', 'localtime', '+1 hour')\n          = strftime('%F %H:00:00', timestamp)\n)\n\nSELECT\n    col1,\n    col2,\n    col3,\n    col4,\n    col5\nFROM (\n    SELECT\n        text1   AS col1,\n        text2   AS col2,\n        text3   AS col3,\n        text4   AS col4,\n        text5   AS col5,\n        action\n    FROM action_measures\n\n    UNION ALL\n\n    SELECT\n        content1 AS col1,\n        content2 AS col2,\n        content3 AS col3,\n        content4 AS col4,\n        content5 AS col5,\n        action\n    FROM action_measures\n) am\nCROSS JOIN solar\nWHERE action = (SELECT action FROM decision)\n  AND solar.solar_active = 0;",
     "rawQueryText": "WITH cfg AS (\n    SELECT\n        MAX(CASE WHEN key='solar_threshold' THEN CAST(value AS REAL) END) AS solar_threshold,\n        MAX(CASE WHEN key='min_solar_buffer_threshold' THEN CAST(value AS REAL) END) AS min_buffer,\n        MAX(CASE WHEN key='solar_buffer_threshold' THEN CAST(value AS REAL) END) AS max_buffer\n    FROM meta_config\n),\nbuf AS (\n    SELECT buffer_temp\n    FROM system_snapshot\n    ORDER BY timestamp_mez DESC\n    LIMIT 1\n),\nsolar AS (\n    SELECT\n        CASE\n            WHEN d.radiation > cfg.solar_threshold\n             AND buf.buffer_temp BETWEEN cfg.min_buffer AND cfg.max_buffer\n            THEN 1 ELSE 0\n        END AS solar_active\n    FROM decision_logic d\n    CROSS JOIN cfg\n    CROSS JOIN buf\n    WHERE strftime('%F %H:00:00', 'now', 'localtime', '+1 hour')\n          = strftime('%F %H:00:00', d.timestamp)\n    LIMIT 1\n),\ndecision AS (\n    SELECT action\n    FROM decision_logic\n    WHERE strftime('%F %H:00:00', 'now', 'localtime', '+1 hour')\n          = strftime('%F %H:00:00', timestamp)\n)\n\nSELECT\n    col1,\n    col2,\n    col3,\n    col4,\n    col5\nFROM (\n    SELECT\n        text1   AS col1,\n        text2   AS col2,\n        text3   AS col3,\n        text4   AS col4,\n        text5   AS col5,\n        action\n    FROM action_measures\n\n    UNION ALL\n\n    SELECT\n        content1 AS col1,\n        content2 AS col2,\n        content3 AS col3,\n        content4 AS col4,\n        content5 AS col5,\n        action\n    FROM action_measures\n) am\nCROSS JOIN solar\nWHERE action = (SELECT action FROM decision)\n  AND solar.solar_active = 0;",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Aktions-Zeitplan",
   "type": "state-timeline",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "queryText": "SELECT  CAST(strftime('%s', time_start, 'utc') AS INTEGER) AS time,\r\n       \r\n    CASE\r\n        WHEN action = 'HEAT_NOW' THEN '1 HEAT_NOW'\r\n        WHEN action = 'HEAT_MIDDAY' THEN NULL\r\n        WHEN action = 'REDUCE' THEN NULL\r\n        WHEN action = 'STABLE' THEN NULL\r\n        END as '       '\r\n    from aktions_zustaende\r\n    where installation_id = 1234567 and \r\n          datetime(time_start) >= datetime('now', 'localtime') \r\norder by time_start asc\r\n       \r\n\r\n",
     "rawQueryText": "SELECT  CAST(strftime('%s', time_start, 'utc') AS INTEGER) AS time,\r\n       \r\n    CASE\r\n        WHEN action = 'HEAT_NOW' THEN '1 HEAT_NOW'\r\n        WHEN action = 'HEAT_MIDDAY' THEN NULL\r\n        WHEN action = 'REDUCE' THEN NULL\r\n        WHEN action = 'STABLE' THEN NULL\r\n        END as '       '\r\n    from aktions_zustaende\r\n    where installation_id = ${anlage_id} and \r\n          datetime(time_start) >= datetime('now', 'localtime') \r\norder by time_start asc\r\n       \r\n\r\n",
     "rawSql": "SELECT timestamp as time, pv_kw as value FROM pv_estimate ORDER BY timestamp;",
     "timeColumns": [
      "time",
      "ts"
     ]
    },
    {
     "queryText": "SELECT  CAST(strftime('%s', time_start, 'utc') AS INTEGER) AS time,\n       \n    CASE\n        WHEN action = 'HEAT_NOW' THEN NULL\n        WHEN action = 'HEAT_MIDDAY' THEN '2 HEAT_MIDDAY'\n        WHEN action = 'REDUCE' THEN NULL\n        WHEN action = 'STABLE' THEN NULL\n        END as '       '\n    from aktions_zustaende\n    where installation_id = 1234567 and \n          datetime(time_start) >= datetime('now', 'localtime') \norder by time_start asc",
     "rawQueryText": "SELECT  CAST(strftime('%s', time_start, 'utc') AS INTEGER) AS time,\n       \n    CASE\n        WHEN action = 'HEAT_NOW' THEN NULL\n        WHEN action = 'HEAT_MIDDAY' THEN '2 HEAT_MIDDAY'\n        WHEN action = 'REDUCE' THEN NULL\n        WHEN action = 'STABLE' THEN NULL\n        END as '       '\n    from aktions_zustaende\n    where installation_id = ${anlage_id} and \n          datetime(time_start) >= datetime('now', 'localtime') \norder by time_start asc",
     "timeColumns": [
      "time",
      "ts"
     ]
    },
    {
     "queryText": "SELECT  CAST(strftime('%s', time_start, 'utc') AS INTEGER) AS time,\n       \n    CASE\n        WHEN action = 'HEAT_NOW' THEN NULL\n        WHEN action = 'HEAT_MIDDAY' THEN NULL\n        WHEN action = 'REDUCE' THEN '3 REDUCE'\n        WHEN action = 'STABLE' THEN NULL\n        END as '       '\n    from aktions_zustaende\n    where installation_id = 1234567 and \n          datetime(time_start) >= datetime('now', 'localtime') \norder by time_start asc",
     "rawQueryText": "SELECT  CAST(strftime('%s', time_start, 'utc') AS INTEGER) AS time,\n       \n    CASE\n        WHEN action = 'HEAT_NOW' THEN NULL\n        WHEN action = 'HEAT_MIDDAY' THEN NULL\n        WHEN action = 'REDUCE' THEN '3 REDUCE'\n        WHEN action = 'STABLE' THEN NULL\n        END as '       '\n    from aktions_zustaende\n    where installation_id = ${anlage_id} and \n          datetime(time_start) >= datetime('now', 'localtime') \norder by time_start asc",
     "timeColumns": [
      "time",
      "ts"
     ]
    },
    {
     "queryText": "SELECT  CAST(strftime('%s', time_start, 'utc') AS INTEGER) AS time,\n       \n    CASE\n        WHEN action = 'HEAT_NOW' THEN NULL\n        WHEN action = 'HEAT_MIDDAY' THEN NULL\n        WHEN action = 'REDUCE' THEN NULL\n        WHEN action = 'STABLE' THEN '4 STABLE'\n        END as '       '\n    from aktions_zustaende\n    where installation_id = 1234567 and \n          datetime(time_start) >= datetime('now', 'localtime') \norder by time_start asc",
     "rawQueryText": "SELECT  CAST(strftime('%s', time_start, 'utc') AS INTEGER) AS time,\n       \n    CASE\n        WHEN action = 'HEAT_NOW' THEN NULL\n        WHEN action = 'HEAT_MIDDAY' THEN NULL\n        WHEN action = 'REDUCE' THEN NULL\n        WHEN action = 'STABLE' THEN '4 STABLE'\n        END as '       '\n    from aktions_zustaende\n    where installation_id = ${anlage_id} and \n          datetime(time_start) >= datetime('now', 'localtime') \norder by time_start asc",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 }, "options": { "content": "###\n" } },
  {
   "title": "ΔT (12h) Prognose aktuell",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT datetime(timestamp), datetime('now', 'localtime'),\r\n        temp_12h - temp_now as date_diff\r\n        FROM weather_forecast\r\n        where datetime(timestamp) >=  datetime('now', 'localtime')\r\n        ORDER BY timestamp ASC\r\n        LIMIT 1\r\n   ",
     "rawQueryText": "SELECT datetime(timestamp), datetime('now', 'localtime'),\r\n        temp_12h - temp_now as date_diff\r\n        FROM weather_forecast\r\n        where datetime(timestamp) >=  datetime('now', 'localtime')\r\n        ORDER BY timestamp ASC\r\n        LIMIT 1\r\n   ",
     "rawSql": "SELECT timestamp as time, delta_12h as value FROM weather_trend ORDER BY timestamp;",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Komfortzeit",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 3, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT \r\n(select value from meta_config where key = 'temp_verlust_gebaeude') *\r\n(select value from meta_config where key = 'comfort_time_reference_value')\r\n/\r\ncooling_rate\r\nas comfort_time,\r\n'Std.' as text\r\nfrom cooling_rate\r\n where datetime(timestamp) >=  datetime('now', 'localtime')\r\n        ORDER BY timestamp ASC\r\n        LIMIT 1\r\n",
     "rawQueryText": "SELECT \r\n(select value from meta_config where key = 'temp_verlust_gebaeude') *\r\n(select value from meta_config where key = 'comfort_time_reference_value')\r\n/\r\ncooling_rate\r\nas comfort_time,\r\n'Std.' as text\r\nfrom cooling_rate\r\n where datetime(timestamp) >=  datetime('now', 'localtime')\r\n        ORDER BY timestamp ASC\r\n        LIMIT 1\r\n",
     "rawSql": "SELECT timestamp as time, delta_12h as value FROM weather_trend ORDER BY timestamp;",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "nächstes PV-Fenster",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 5, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT strftime('%F %T', timestamp), datetime(1776642015706/1000, 'unixepoch', 'localtime\n'),\n  strftime('%d.%m.%Y %H:%M', timestamp) as Zeitfenster,\n  pv_kw as 'Wert'\n FROM pv_window\n        WHERE pv_next_peak > (SELECT value FROM meta_config WHERE key='pv_threshold') and datetime(timestamp) >= datetime('now', 'localtime') and \n        (strftime('%F %T', timestamp) between datetime(1776469215706/1000, 'unixepoch', 'localtime') and datetime(1776642015706/1000, 'unixepoch', 'localtime'))\n        ORDER BY timestamp asc, pv_next_peak DESC\n        LIMIT 1\n\n",
     "rawQueryText": "SELECT strftime('%F %T', timestamp), datetime($__to/1000, 'unixepoch', 'localtime\n'),\n  strftime('%d.%m.%Y %H:%M', timestamp) as Zeitfenster,\n  pv_kw as 'Wert'\n FROM pv_window\n        WHERE pv_next_peak > (SELECT value FROM meta_config WHERE key='pv_threshold') and datetime(timestamp) >= datetime('now', 'localtime') and \n        (strftime('%F %T', timestamp) between datetime($__from/1000, 'unixepoch', 'localtime') and datetime($__to/1000, 'unixepoch', 'localtime'))\n        ORDER BY timestamp asc, pv_next_peak DESC\n        LIMIT 1\n\n",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "PV-Leistung und Peak nächstes PV-Fenster",
   "type": "stat",
   "gridPos": { "h": 3, "w": 7, "x": 8, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "WITH start_window AS (\n    SELECT timestamp\n    FROM (\n        SELECT \n            timestamp,\n            MAX(pv_kw) OVER (\n                ORDER BY timestamp\n                ROWS BETWEEN CURRENT ROW AND 3 FOLLOWING\n            ) AS pv_next_peak\n        FROM pv_estimate\n        WHERE datetime(timestamp) >= datetime('now','localtime')\n          AND strftime('%F %T', timestamp) BETWEEN datetime($__from/1000, 'unixepoch', 'localtime') \n                                              AND datetime($__to/1000, 'unixepoch', 'localtime')\n    )\n    WHERE pv_next_peak > (SELECT value FROM meta_config WHERE key='pv_threshold')\n    ORDER BY timestamp\n    LIMIT 1\n),\n\nwindow_rows AS (\n    SELECT timestamp, \n    pv_kw\n    FROM pv_estimate\n    WHERE timestamp >= (SELECT timestamp FROM start_window)\n    ORDER BY timestamp\n    LIMIT 4\n),\n\npv_leistung as (\n    select \n    sum(pv_kw) as pv_leistung_pv_window\n    from window_rows\n)\n\nSELECT \n   (Select pv_leistung_pv_window from pv_leistung) as 'PV-Leistung',\n   pv_kw AS Peak\n   FROM window_rows\nORDER BY pv_kw DESC\nLIMIT 1;",
     "rawQueryText": "WITH start_window AS (\n    SELECT timestamp\n    FROM (\n        SELECT \n            timestamp,\n            MAX(pv_kw) OVER (\n                ORDER BY timestamp\n                ROWS BETWEEN CURRENT ROW AND 3 FOLLOWING\n            ) AS pv_next_peak\n        FROM pv_estimate\n        WHERE datetime(timestamp) >= datetime('now','localtime')\n          AND strftime('%F %T', timestamp) BETWEEN datetime($__from/1000, 'unixepoch', 'localtime') \n                                              AND datetime($__to/1000, 'unixepoch', 'localtime')\n    )\n    WHERE pv_next_peak > (SELECT value FROM meta_config WHERE key='pv_threshold')\n    ORDER BY timestamp\n    LIMIT 1\n),\n\nwindow_rows AS (\n    SELECT timestamp, \n    pv_kw\n    FROM pv_estimate\n    WHERE timestamp >= (SELECT timestamp FROM start_window)\n    ORDER BY timestamp\n    LIMIT 4\n),\n\npv_leistung as (\n    select \n    sum(pv_kw) as pv_leistung_pv_window\n    from window_rows\n)\n\nSELECT \n   (Select pv_leistung_pv_window from pv_leistung) as 'PV-Leistung',\n   pv_kw AS Peak\n   FROM window_rows\nORDER BY pv_kw DESC\nLIMIT 1;",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT \ndatetime(strftime('%F %T', timestamp)),\npv_kw / (SELECT value FROM meta_config WHERE key='pv_kwp') * 100 as Prozent\nFROM pv_estimate\nwhere datetime(strftime('%F %T', timestamp)) >= datetime('now', 'localtime')\nORDER BY timestamp asc\nLimit 1\n",
     "rawQueryText": "SELECT \ndatetime(strftime('%F %T', timestamp)),\npv_kw / (SELECT value FROM meta_config WHERE key='pv_kwp') * 100 as Prozent\nFROM pv_estimate\nwhere datetime(strftime('%F %T', timestamp)) >= datetime('now', 'localtime')\nORDER BY timestamp asc\nLimit 1\n",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "PV Leistung",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT timestamp, pv_kw,datetime('now', 'localtime'),\n  strftime('%H:%M', timestamp) as Uhrzeit,\n    pv_quality\nFROM pv_logic\nwhere datetime(strftime('%F %T', timestamp)) >= datetime('now', 'localtime')\norder by timestamp asc\nLimit 1",
     "rawQueryText": "SELECT timestamp, pv_kw,datetime('now', 'localtime'),\n  strftime('%H:%M', timestamp) as Uhrzeit,\n    pv_quality\nFROM pv_logic\nwhere datetime(strftime('%F %T', timestamp)) >= datetime('now', 'localtime')\norder by timestamp asc\nLimit 1",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Einstrahlung",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "Wm2" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT timestamp, pv_kw,datetime('now', 'localtime'),\n  strftime('%H:%M', timestamp) as Uhrzeit,\n  radiation,\n    case\n        WHEN radiation > 300 THEN 'STRONG'\n        WHEN radiation > 150 THEN 'WEAK'\n        ELSE 'NONE'\n        END AS radiation_quality\nFROM pv_estimate\nwhere datetime(strftime('%F %T', timestamp)) >= datetime('now', 'localtime')\norder by timestamp asc\nLimit 1",
     "rawQueryText": "SELECT timestamp, pv_kw,datetime('now', 'localtime'),\n  strftime('%H:%M', timestamp) as Uhrzeit,\n  radiation,\n    case\n        WHEN radiation > 300 THEN 'STRONG'\n        WHEN radiation > 150 THEN 'WEAK'\n        ELSE 'NONE'\n        END AS radiation_quality\nFROM pv_estimate\nwhere datetime(strftime('%F %T', timestamp)) >= datetime('now', 'localtime')\norder by timestamp asc\nLimit 1",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 }, "options": { "content": "###\n" } },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 20 },
   "options": {
    "content": "### 48-Stunden-Prognose der Energiemanagement-Parameter\n"
   }
  },
  {
   "title": "Temperaturtrend-Entwicklung & PV-Leistung mit PV-Fenster ",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "queryText": "SELECT \r\n  CAST(strftime('%s', timestamp, 'utc') AS INTEGER) AS time,\r\n  pv_kw as 'PV-Leistung (Forecast)'\r\nFROM pv_estimate\r\nwhere strftime('%F %H:00:00', timestamp) between datetime(1776488591852/1000, 'unixepoch', 'localtime') \r\n      and datetime(1776661391852/1000, 'unixepoch', 'localtime')",
     "rawQueryText": "SELECT \r\n  CAST(strftime('%s', timestamp, 'utc') AS INTEGER) AS time,\r\n  pv_kw as 'PV-Leistung (Forecast)'\r\nFROM pv_estimate\r\nwhere strftime('%F %H:00:00', timestamp) between datetime($__from/1000, 'unixepoch', 'localtime') \r\n      and datetime($__to/1000, 'unixepoch', 'localtime')",
     "rawSql": "SELECT timestamp as time, pv_kw as value FROM pv_estimate ORDER BY timestamp;",
     "timeColumns": [
      "time",
      "ts"
     ]
    },
    {
     "queryText": "SELECT\n   cast(strftime('%s', timestamp, 'utc') as integer) as time,\n   delta_12h as 'ΔT (12h)-Trend (Forecast)' \n   from weather_trend\nwhere strftime('%F %H:00:00', timestamp) between datetime(1776488591852/1000, 'unixepoch', 'localtime') \n      and datetime(1776661391852/1000, 'unixepoch', 'localtime')",
     "rawQueryText": "SELECT\n   cast(strftime('%s', timestamp, 'utc') as integer) as time,\n   delta_12h as 'ΔT (12h)-Trend (Forecast)' \n   from weather_trend\nwhere strftime('%F %H:00:00', timestamp) between datetime($__from/1000, 'unixepoch', 'localtime') \n      and datetime($__to/1000, 'unixepoch', 'localtime')",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "1 Heizen vorziehen",
   "type": "table",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 29 },
   "targets": [
    {
     "queryText": "SELECT *\nFROM (\n\n    SELECT *\n    FROM (\n        SELECT\n            'ΔT (12h) Prognose aktuell' AS Parameter,\n            COALESCE(printf('%.1f °C', temp_12h - temp_now), '0 °C') AS Wert,\n            COALESCE('fällt um mehr als 3 Grad', '') AS Grenzwert\n        FROM weather_forecast\n        WHERE datetime(timestamp) >= datetime('now', 'localtime')\n        ORDER BY timestamp ASC\n        LIMIT 1\n    )\n\n    UNION ALL\n\n    SELECT *\n    FROM (\n        SELECT\n            'ergänzende Informationen: ' AS Parameter,\n            COALESCE(char(8203), '') AS Wert,\n            COALESCE(char(8203), '') AS Grenzwert\n        FROM pv_window\n        WHERE pv_kw > (SELECT value FROM meta_config WHERE key='pv_threshold')\n          AND datetime(timestamp) >= datetime('now', 'localtime')\n        ORDER BY pv_next_peak DESC\n        LIMIT 1\n    )\n\n    UNION ALL\n\n    SELECT *\n    FROM (\n        SELECT\n            'Komfortzeit' AS Parameter,\n            COALESCE(\n                printf('%.1f',\n                    (SELECT value FROM meta_config WHERE key='temp_verlust_gebaeude')\n                    * (SELECT value FROM meta_config WHERE key='comfort_time_reference_value')\n                    / COALESCE(cooling_rate, 1)\n                ),\n            '0') AS Wert,\n            COALESCE(\n                printf('< %.0f Stunden',\n                    (SELECT value FROM meta_config WHERE key='comfort_time_reference_value')\n                ),\n            '') AS Grenzwert\n        FROM cooling_rate\n        WHERE datetime(timestamp) >= datetime('now', 'localtime')\n        ORDER BY timestamp ASC\n        LIMIT 1\n    )\n\n    UNION ALL\n\n    SELECT *\n    FROM (\n        SELECT \n            'Verdichter-LZ letzte Stunde' AS Parameter,\n            COALESCE(printf('%.0f Minuten', runtime_minutes_1h), '0 Minuten') AS Wert,\n            COALESCE('weniger als 30 Minuten', '') AS Grenzwert\n        FROM system_snapshot\n        WHERE installation_id = ${anlage_id}\n          AND timestamp_mez <= datetime('now','localtime')\n        ORDER BY timestamp_mez DESC\n        LIMIT 1\n    )\n\n    UNION ALL\n\n    SELECT *\n    FROM (\n        SELECT \n            'Kompressorstarts letzte Stunde' AS Parameter,\n            COALESCE(compressor_starts_1h, 0) AS Wert,\n            COALESCE('<= 2', '') AS Grenzwert\n        FROM system_snapshot\n        WHERE installation_id = ${anlage_id}\n          AND timestamp_mez <= datetime('now','localtime')\n        ORDER BY timestamp_mez DESC\n        LIMIT 1\n    )\n\n    UNION ALL\n\n    SELECT *\n    FROM (\n        SELECT \n            'Warmwasser-Temp letzte Stunde' AS Parameter,\n            COALESCE(printf('%.1f °C', dhw_temp), '0 °C') AS Wert,\n            COALESCE('<= 50 Grad', '') AS Grenzwert\n        FROM system_snapshot\n        WHERE installation_id = ${anlage_id}\n          AND timestamp_mez <= datetime('now','localtime')\n        ORDER BY timestamp_mez DESC\n        LIMIT 1\n    )\n\n    UNION ALL\n\n    SELECT * FROM (\n        SELECT '' AS Parameter, '' AS Wert, '' AS Grenzwert\n        UNION ALL\n        SELECT '' , '' , ''\n    )\n\n)\n\nWHERE\n(\n    '${s_decision}' = 'EIN'\n    OR EXISTS (\n        SELECT 1\n        FROM decision_logic\n        WHERE action = 'HEAT_NOW'\n          AND strftime('%F %H:00:00', 'now', 'localtime', '+1 hour')\n              = strftime('%F %H:00:00', timestamp)\n    )\n)",
     "rawQueryText": "SELECT *\nFROM (\n\n    SELECT *\n    FROM (\n        SELECT\n            'ΔT (12h) Prognose aktuell' AS Parameter,\n            COALESCE(printf('%.1f °C', temp_12h - temp_now), '0 °C') AS Wert,\n            COALESCE('fällt um mehr als 3 Grad', '') AS Grenzwert\n        FROM weather_forecast\n        WHERE datetime(timestamp) >= datetime('now', 'localtime')\n        ORDER BY timestamp ASC\n        LIMIT 1\n    )\n\n    UNION ALL\n\n    SELECT *\n    FROM (\n        SELECT\n            'ergänzende Informationen: ' AS Parameter,\n            COALESCE(char(8203), '') AS Wert,\n            COALESCE(char(8203), '') AS Grenzwert\n        FROM pv_window\n        WHERE pv_kw > (SELECT value FROM meta_config WHERE key='pv_threshold')\n          AND datetime(timestamp) >= datetime('now', 'localtime')\n        ORDER BY pv_next_peak DESC\n        LIMIT 1\n    )\n\n    UNION ALL\n\n    SELECT *\n    FROM (\n        SELECT\n            'Komfortzeit' AS Parameter,\n            COALESCE(\n                printf('%.1f',\n                    (SELECT value FROM meta_config WHERE key='temp_verlust_gebaeude')\n                    * (SELECT value FROM meta_config WHERE key='comfort_time_reference_value')\n                    / COALESCE(cooling_rate, 1)\n                ),\n            '0') AS Wert,\n            COALESCE(\n                printf('< %.0f Stunden',\n                    (SELECT value FROM meta_config WHERE key='comfort_time_reference_value')\n                ),\n            '') AS Grenzwert\n        FROM cooling_rate\n        WHERE datetime(timestamp) >= datetime('now', 'localtime')\n        ORDER BY timestamp ASC\n        LIMIT 1\n    )\n\n    UNION ALL\n\n    SELECT *\n    FROM (\n        SELECT \n            'Verdichter-LZ letzte Stunde' AS Parameter,\n            COALESCE(printf('%.0f Minuten', runtime_minutes_1h), '0 Minuten') AS Wert,\n            COALESCE('weniger als 30 Minuten', '') AS Grenzwert\n        FROM system_snapshot\n        WHERE installation_id = ${anlage_id}\n          AND timestamp_mez <= datetime('now','localtime')\n        ORDER BY timestamp_mez DESC\n        LIMIT 1\n    )\n\n    UNION ALL\n\n    SELECT *\n    FROM (\n        SELECT \n            'Kompressorstarts letzte Stunde' AS Parameter,\n            COALESCE(compressor_starts_1h, 0) AS Wert,\n            COALESCE('<= 2', '') AS Grenzwert\n        FROM system_snapshot\n        WHERE installation_id = ${anlage_id}\n          AND timestamp_mez <= datetime('now','localtime')\n        ORDER BY timestamp_mez DESC\n        LIMIT 1\n    )\n\n    UNION ALL\n\n    SELECT *\n    FROM (\n        SELECT \n            'Warmwasser-Temp letzte Stunde' AS Parameter,\n            COALESCE(printf('%.1f °C', dhw_temp), '0 °C') AS Wert,\n            COALESCE('<= 50 Grad', '') AS Grenzwert\n        FROM system_snapshot\n        WHERE installation_id = ${anlage_id}\n          AND timestamp_mez <= datetime('now','localtime')\n        ORDER BY timestamp_mez DESC\n        LIMIT 1\n    )\n\n    UNION ALL\n\n    SELECT * FROM (\n        SELECT '' AS Parameter, '' AS Wert, '' AS Grenzwert\n        UNION ALL\n        SELECT '' , '' , ''\n    )\n\n)\n\nWHERE\n(\n    '${s_decision}' = 'EIN'\n    OR EXISTS (\n        SELECT 1\n        FROM decision_logic\n        WHERE action = 'HEAT_NOW'\n          AND strftime('%F %H:00:00', 'now', 'localtime', '+1 hour')\n              = strftime('%F %H:00:00', timestamp)\n    )\n)",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "2 PV nutzen",
   "type": "table",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 29 },
   "targets": [
    {
     "queryText": "SELECT *\nFROM (\n\n    SELECT *\n    FROM (\n        SELECT\n            'ΔT (12h) Prognose aktuell' AS Parameter,\n            COALESCE(printf('%.1f °C', temp_12h - temp_now), '0 °C') AS Wert,\n            COALESCE('fällt um mehr als 3 Grad', '') AS Grenzwert\n        FROM weather_forecast\n        WHERE datetime(timestamp) >= datetime('now', 'localtime')\n        ORDER BY timestamp ASC\n        LIMIT 1\n    )\n\n    UNION ALL\n\n    SELECT *\n    FROM (\n        SELECT\n            'nächster PV Peak' AS Parameter,\n            COALESCE(printf('%.2f kW', pv_next_peak), '0.00 kW') AS Wert,\n            COALESCE('>= 2.0 KW', '') AS Grenzwert\n        FROM pv_window\n        WHERE pv_next_peak > (SELECT value FROM meta_config WHERE key='pv_threshold')\n          AND datetime(timestamp) >= datetime('now', 'localtime')\n          AND (\n              strftime('%F %T', timestamp)\n              BETWEEN datetime($__from/1000, 'unixepoch', 'localtime')\n                  AND datetime($__to/1000, 'unixepoch', 'localtime')\n          )\n        LIMIT 1\n    )\n\n    UNION ALL\n\n    SELECT *\n    FROM (\n        SELECT\n            'ergänzende Informationen: ' AS Parameter,\n            COALESCE(char(8203), '') AS Wert,\n            COALESCE(char(8203), '') AS Grenzwert\n        FROM pv_window\n        WHERE pv_kw > (SELECT value FROM meta_config WHERE key='pv_threshold')\n          AND datetime(timestamp) >= datetime('now', 'localtime')\n        ORDER BY pv_next_peak DESC\n        LIMIT 1\n    )\n\n    UNION ALL\n\n    SELECT *\n    FROM (\n        SELECT\n            'Komfortzeit' AS Parameter,\n            COALESCE(\n                printf('%.1f',\n                    (SELECT value FROM meta_config WHERE key='temp_verlust_gebaeude') * 6\n                    / COALESCE(cooling_rate, 1)\n                ),\n            '0') AS Wert,\n            COALESCE(char(8203), '') AS Grenzwert\n        FROM cooling_rate\n        WHERE datetime(timestamp) >= datetime('now', 'localtime')\n        ORDER BY timestamp ASC\n        LIMIT 1\n    )\n\n    UNION ALL\n\n    SELECT *\n    FROM (\n        SELECT\n            'nächstes PV-Fenster' AS Parameter,\n            COALESCE(\n                printf('in ca. %.1f Stunden',\n                    (julianday(timestamp) - julianday('now','localtime')) * 24.0\n                ),\n            '0 h') AS Wert,\n            COALESCE('<= Komfortzeit', '') AS Grenzwert\n        FROM pv_window\n        WHERE pv_next_peak > 2\n          AND datetime(timestamp) >= datetime('now', 'localtime')\n          AND (\n              strftime('%F %T', timestamp)\n              BETWEEN datetime($__from/1000, 'unixepoch', 'localtime')\n                  AND datetime($__to/1000, 'unixepoch', 'localtime')\n          )\n        ORDER BY timestamp ASC\n        LIMIT 1\n    )\n\n    UNION ALL\n\n    SELECT *\n    FROM (\n        SELECT \n            'Verdichter-LZ letzte Stunde' AS Parameter,\n            COALESCE(printf('%.0f Minuten', runtime_minutes_1h), '0 Minuten') AS Wert,\n            COALESCE('25 - 45 Minuten', '') AS Grenzwert\n        FROM system_snapshot\n        WHERE installation_id = ${anlage_id}\n          AND timestamp_mez <= datetime('now','localtime')\n        ORDER BY timestamp_mez DESC\n        LIMIT 1\n    )\n\n    UNION ALL\n\n    SELECT *\n    FROM (\n        SELECT \n            'Kompressorstarts letzte Stunde' AS Parameter,\n            COALESCE(compressor_starts_1h, 0) AS Wert,\n            COALESCE('<= 2', '') AS Grenzwert\n        FROM system_snapshot\n        WHERE installation_id = ${anlage_id}\n          AND timestamp_mez <= datetime('now','localtime')\n        ORDER BY timestamp_mez DESC\n        LIMIT 1\n    )\n\n    UNION ALL\n\n    SELECT *\n    FROM (\n        SELECT \n            'Warmwasser-Temp letzte Stunde' AS Parameter,\n            COALESCE(printf('%.1f °C', dhw_temp), '0 °C') AS Wert,\n            COALESCE('> 50 Grad', '') AS Grenzwert\n        FROM system_snapshot\n        WHERE installation_id = ${anlage_id}\n          AND timestamp_mez <= datetime('now','localtime')\n        ORDER BY timestamp_mez DESC\n        LIMIT 1\n    )\n\n)\n\nWHERE\n(\n    '${s_decision}' = 'EIN'\n    OR EXISTS (\n        SELECT 1\n        FROM decision_logic\n        WHERE action = 'HEAT_MIDDAY'\n          AND strftime('%F %H:00:00', 'now', 'localtime', '+1 hour')\n              = strftime('%F %H:00:00', timestamp)\n    )\n)",
     "rawQueryText": "SELECT *\nFROM (\n\n    SELECT *\n    FROM (\n        SELECT\n            'ΔT (12h) Prognose aktuell' AS Parameter,\n            COALESCE(printf('%.1f °C', temp_12h - temp_now), '0 °C') AS Wert,\n            COALESCE('fällt um mehr als 3 Grad', '') AS Grenzwert\n        FROM weather_forecast\n        WHERE datetime(timestamp) >= datetime('now', 'localtime')\n        ORDER BY timestamp ASC\n        LIMIT 1\n    )\n\n    UNION ALL\n\n    SELECT *\n    FROM (\n        SELECT\n            'nächster PV Peak' AS Parameter,\n            COALESCE(printf('%.2f kW', pv_next_peak), '0.00 kW') AS Wert,\n            COALESCE('>= 2.0 KW', '') AS Grenzwert\n        FROM pv_window\n        WHERE pv_next_peak > (SELECT value FROM meta_config WHERE key='pv_threshold')\n          AND datetime(timestamp) >= datetime('now', 'localtime')\n          AND (\n              strftime('%F %T', timestamp)\n              BETWEEN datetime($__from/1000, 'unixepoch', 'localtime')\n                  AND datetime($__to/1000, 'unixepoch', 'localtime')\n          )\n        LIMIT 1\n    )\n\n    UNION ALL\n\n    SELECT *\n    FROM (\n        SELECT\n            'ergänzende Informationen: ' AS Parameter,\n            COALESCE(char(8203), '') AS Wert,\n            COALESCE(char(8203), '') AS Grenzwert\n        FROM pv_window\n        WHERE pv_kw > (SELECT value FROM meta_config WHERE key='pv_threshold')\n          AND datetime(timestamp) >= datetime('now', 'localtime')\n        ORDER BY pv_next_peak DESC\n        LIMIT 1\n    )\n\n    UNION ALL\n\n    SELECT *\n    FROM (\n        SELECT\n            'Komfortzeit' AS Parameter,\n            COALESCE(\n                printf('%.1f',\n                    (SELECT value FROM meta_config WHERE key='temp_verlust_gebaeude') * 6\n                    / COALESCE(cooling_rate, 1)\n                ),\n            '0') AS Wert,\n            COALESCE(char(8203), '') AS Grenzwert\n        FROM cooling_rate\n        WHERE datetime(timestamp) >= datetime('now', 'localtime')\n        ORDER BY timestamp ASC\n        LIMIT 1\n    )\n\n    UNION ALL\n\n    SELECT *\n    FROM (\n        SELECT\n            'nächstes PV-Fenster' AS Parameter,\n            COALESCE(\n                printf('in ca. %.1f Stunden',\n                    (julianday(timestamp) - julianday('now','localtime')) * 24.0\n                ),\n            '0 h') AS Wert,\n            COALESCE('<= Komfortzeit', '') AS Grenzwert\n        FROM pv_window\n        WHERE pv_next_peak > 2\n          AND datetime(timestamp) >= datetime('now', 'localtime')\n          AND (\n              strftime('%F %T', timestamp)\n              BETWEEN datetime($__from/1000, 'unixepoch', 'localtime')\n                  AND datetime($__to/1000, 'unixepoch', 'localtime')\n          )\n        ORDER BY timestamp ASC\n        LIMIT 1\n    )\n\n    UNION ALL\n\n    SELECT *\n    FROM (\n        SELECT \n            'Verdichter-LZ letzte Stunde' AS Parameter,\n            COALESCE(printf('%.0f Minuten', runtime_minutes_1h), '0 Minuten') AS Wert,\n            COALESCE('25 - 45 Minuten', '') AS Grenzwert\n        FROM system_snapshot\n        WHERE installation_id = ${anlage_id}\n          AND timestamp_mez <= datetime('now','localtime')\n        ORDER BY timestamp_mez DESC\n        LIMIT 1\n    )\n\n    UNION ALL\n\n    SELECT *\n    FROM (\n        SELECT \n            'Kompressorstarts letzte Stunde' AS Parameter,\n            COALESCE(compressor_starts_1h, 0) AS Wert,\n            COALESCE('<= 2', '') AS Grenzwert\n        FROM system_snapshot\n        WHERE installation_id = ${anlage_id}\n          AND timestamp_mez <= datetime('now','localtime')\n        ORDER BY timestamp_mez DESC\n        LIMIT 1\n    )\n\n    UNION ALL\n\n    SELECT *\n    FROM (\n        SELECT \n            'Warmwasser-Temp letzte Stunde' AS Parameter,\n            COALESCE(printf('%.1f °C', dhw_temp), '0 °C') AS Wert,\n            COALESCE('> 50 Grad', '') AS Grenzwert\n        FROM system_snapshot\n        WHERE installation_id = ${anlage_id}\n          AND timestamp_mez <= datetime('now','localtime')\n        ORDER BY timestamp_mez DESC\n        LIMIT 1\n    )\n\n)\n\nWHERE\n(\n    '${s_decision}' = 'EIN'\n    OR EXISTS (\n        SELECT 1\n        FROM decision_logic\n        WHERE action = 'HEAT_MIDDAY'\n          AND strftime('%F %H:00:00', 'now', 'localtime', '+1 hour')\n              = strftime('%F %H:00:00', timestamp)\n    )\n)",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "3 Heizen verschieben",
   "type": "table",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "queryText": "SELECT *\nFROM (\n\n    SELECT *\n    FROM (\n        SELECT\n            'ΔT (12h) Prognose aktuell' AS Parameter,\n            COALESCE(printf('%.1f °C', temp_12h - temp_now), '0 °C') AS Wert,\n            COALESCE('> 3 Grad', '') AS Grenzwert\n        FROM weather_forecast\n        WHERE datetime(timestamp) >= datetime('now', 'localtime')\n        ORDER BY timestamp ASC\n        LIMIT 1\n    )\n\n    UNION ALL\n\n    SELECT *\n    FROM (\n        SELECT\n            'ergänzende Informationen: ' AS Parameter,\n            COALESCE(char(8203), '') AS Wert,\n            COALESCE(char(8203), '') AS Grenzwert\n        FROM pv_window\n        WHERE pv_kw > (SELECT value FROM meta_config WHERE key='pv_threshold')\n          AND datetime(timestamp) >= datetime('now', 'localtime')\n        ORDER BY pv_next_peak DESC\n        LIMIT 1\n    )\n\n    UNION ALL\n\n    SELECT *\n    FROM (\n        SELECT\n            'Komfortzeit' AS Parameter,\n            COALESCE(\n                printf('%.1f',\n                    (SELECT value FROM meta_config WHERE key='temp_verlust_gebaeude')\n                    * (SELECT value FROM meta_config WHERE key='comfort_time_reference_value')\n                    / COALESCE(cooling_rate, 1)\n                ),\n            '0') AS Wert,\n            COALESCE('> 6 Stunden', '') AS Grenzwert\n        FROM cooling_rate\n        WHERE datetime(timestamp) >= datetime('now', 'localtime')\n        ORDER BY timestamp ASC\n        LIMIT 1\n    )\n\n    UNION ALL\n\n    SELECT *\n    FROM (\n        SELECT\n            'nächstes PV-Fenster' AS Parameter,\n            COALESCE(\n                printf('in ca. %.1f Stunden',\n                    (julianday(timestamp) - julianday('now','localtime')) * 24.0\n                ),\n            '0 h') AS Wert,\n            COALESCE('<= Komfortzeit', '') AS Grenzwert\n        FROM pv_window\n        WHERE pv_next_peak > 2\n          AND datetime(timestamp) >= datetime('now', 'localtime')\n          AND (\n              strftime('%F %T', timestamp)\n              BETWEEN datetime($__from/1000, 'unixepoch', 'localtime')\n                  AND datetime($__to/1000, 'unixepoch', 'localtime')\n          )\n        ORDER BY timestamp ASC\n        LIMIT 1\n    )\n\n    UNION ALL\n\n    SELECT *\n    FROM (\n        SELECT \n            'Kompressor-Laufzeit letzte Stunde' AS Parameter,\n            COALESCE(printf('%.0f Minuten', runtime_minutes_1h), '0 Minuten') AS Wert,\n            COALESCE('< 20', '') AS Grenzwert\n        FROM system_snapshot\n        WHERE installation_id = ${anlage_id}\n          AND timestamp_mez <= datetime('now','localtime')\n        ORDER BY timestamp_mez DESC\n        LIMIT 1\n    )\n\n    UNION ALL\n\n    SELECT *\n    FROM (\n        SELECT \n            'Kompressorstarts letzte Stunde' AS Parameter,\n            COALESCE(compressor_starts_1h, 0) AS Wert,\n            COALESCE('<= 2', '') AS Grenzwert\n        FROM system_snapshot\n        WHERE installation_id = ${anlage_id}\n          AND timestamp_mez <= datetime('now','localtime')\n        ORDER BY timestamp_mez DESC\n        LIMIT 1\n    )\n\n    UNION ALL\n\n    SELECT *\n    FROM (\n        SELECT \n            'Warmwasser-Temp letzte Stunde' AS Parameter,\n            COALESCE(printf('%.1f °C', dhw_temp), '0 °C') AS Wert,\n            COALESCE('> 50 Grad', '') AS Grenzwert\n        FROM system_snapshot\n        WHERE installation_id = ${anlage_id}\n          AND timestamp_mez <= datetime('now','localtime')\n        ORDER BY timestamp_mez DESC\n        LIMIT 1\n    )\n\n    UNION ALL\n\n    SELECT *\n    FROM (\n        SELECT\n            '' AS Parameter,\n            '' AS Wert,\n            '' AS Grenzwert\n        LIMIT 1\n    )\n\n)\n\nWHERE\n(\n    '${s_decision}' = 'EIN'\n    OR EXISTS (\n        SELECT 1\n        FROM decision_logic\n        WHERE action = 'REDUCE'\n          AND strftime('%F %H:00:00', 'now', 'localtime', '+1 hour')\n              = strftime('%F %H:00:00', timestamp)\n    )\n)\n      \n",
     "rawQueryText": "SELECT *\nFROM (\n\n    SELECT *\n    FROM (\n        SELECT\n            'ΔT (12h) Prognose aktuell' AS Parameter,\n            COALESCE(printf('%.1f °C', temp_12h - temp_now), '0 °C') AS Wert,\n            COALESCE('> 3 Grad', '') AS Grenzwert\n        FROM weather_forecast\n        WHERE datetime(timestamp) >= datetime('now', 'localtime')\n        ORDER BY timestamp ASC\n        LIMIT 1\n    )\n\n    UNION ALL\n\n    SELECT *\n    FROM (\n        SELECT\n            'ergänzende Informationen: ' AS Parameter,\n            COALESCE(char(8203), '') AS Wert,\n            COALESCE(char(8203), '') AS Grenzwert\n        FROM pv_window\n        WHERE pv_kw > (SELECT value FROM meta_config WHERE key='pv_threshold')\n          AND datetime(timestamp) >= datetime('now', 'localtime')\n        ORDER BY pv_next_peak DESC\n        LIMIT 1\n    )\n\n    UNION ALL\n\n    SELECT *\n    FROM (\n        SELECT\n            'Komfortzeit' AS Parameter,\n            COALESCE(\n                printf('%.1f',\n                    (SELECT value FROM meta_config WHERE key='temp_verlust_gebaeude')\n                    * (SELECT value FROM meta_config WHERE key='comfort_time_reference_value')\n                    / COALESCE(cooling_rate, 1)\n                ),\n            '0') AS Wert,\n            COALESCE('> 6 Stunden', '') AS Grenzwert\n        FROM cooling_rate\n        WHERE datetime(timestamp) >= datetime('now', 'localtime')\n        ORDER BY timestamp ASC\n        LIMIT 1\n    )\n\n    UNION ALL\n\n    SELECT *\n    FROM (\n        SELECT\n            'nächstes PV-Fenster' AS Parameter,\n            COALESCE(\n                printf('in ca. %.1f Stunden',\n                    (julianday(timestamp) - julianday('now','localtime')) * 24.0\n                ),\n            '0 h') AS Wert,\n            COALESCE('<= Komfortzeit', '') AS Grenzwert\n        FROM pv_window\n        WHERE pv_next_peak > 2\n          AND datetime(timestamp) >= datetime('now', 'localtime')\n          AND (\n              strftime('%F %T', timestamp)\n              BETWEEN datetime($__from/1000, 'unixepoch', 'localtime')\n                  AND datetime($__to/1000, 'unixepoch', 'localtime')\n          )\n        ORDER BY timestamp ASC\n        LIMIT 1\n    )\n\n    UNION ALL\n\n    SELECT *\n    FROM (\n        SELECT \n            'Kompressor-Laufzeit letzte Stunde' AS Parameter,\n            COALESCE(printf('%.0f Minuten', runtime_minutes_1h), '0 Minuten') AS Wert,\n            COALESCE('< 20', '') AS Grenzwert\n        FROM system_snapshot\n        WHERE installation_id = ${anlage_id}\n          AND timestamp_mez <= datetime('now','localtime')\n        ORDER BY timestamp_mez DESC\n        LIMIT 1\n    )\n\n    UNION ALL\n\n    SELECT *\n    FROM (\n        SELECT \n            'Kompressorstarts letzte Stunde' AS Parameter,\n            COALESCE(compressor_starts_1h, 0) AS Wert,\n            COALESCE('<= 2', '') AS Grenzwert\n        FROM system_snapshot\n        WHERE installation_id = ${anlage_id}\n          AND timestamp_mez <= datetime('now','localtime')\n        ORDER BY timestamp_mez DESC\n        LIMIT 1\n    )\n\n    UNION ALL\n\n    SELECT *\n    FROM (\n        SELECT \n            'Warmwasser-Temp letzte Stunde' AS Parameter,\n            COALESCE(printf('%.1f °C', dhw_temp), '0 °C') AS Wert,\n            COALESCE('> 50 Grad', '') AS Grenzwert\n        FROM system_snapshot\n        WHERE installation_id = ${anlage_id}\n          AND timestamp_mez <= datetime('now','localtime')\n        ORDER BY timestamp_mez DESC\n        LIMIT 1\n    )\n\n    UNION ALL\n\n    SELECT *\n    FROM (\n        SELECT\n            '' AS Parameter,\n            '' AS Wert,\n            '' AS Grenzwert\n        LIMIT 1\n    )\n\n)\n\nWHERE\n(\n    '${s_decision}' = 'EIN'\n    OR EXISTS (\n        SELECT 1\n        FROM decision_logic\n        WHERE action = 'REDUCE'\n          AND strftime('%F %H:00:00', 'now', 'localtime', '+1 hour')\n              = strftime('%F %H:00:00', timestamp)\n    )\n)\n      \n",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "4 Keine Änderung",
   "type": "table",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 40 },
   "targets": [
    {
     "queryText": "SELECT *\nFROM (\n\n    SELECT *\n    FROM (\n        SELECT \n            'automatische Anlagen-Steuerung' AS Parameter,\n            COALESCE(char(8203), '') AS Wert,\n            COALESCE(char(8203), '') AS Grenzwert\n        FROM system_snapshot\n        WHERE installation_id = ${anlage_id}\n          AND timestamp_mez <= datetime('now','localtime')\n        ORDER BY timestamp_mez DESC\n        LIMIT 1\n    )\n\n    UNION ALL\n\n    SELECT *\n    FROM (\n        SELECT \n            'ergänzende Informationen: ' AS Parameter,\n            COALESCE(char(8203), '') AS Wert,\n            COALESCE(char(8203), '') AS Grenzwert\n        FROM system_snapshot\n        WHERE installation_id = ${anlage_id}\n          AND timestamp_mez <= datetime('now','localtime')\n        ORDER BY timestamp_mez DESC\n        LIMIT 1\n    )\n\n    UNION ALL\n\n    SELECT *\n    FROM (\n        SELECT\n            'Komfortzeit' AS Parameter,\n            COALESCE(\n                printf('%.1f',\n                    (SELECT value FROM meta_config WHERE key = 'temp_verlust_gebaeude')\n                    * (SELECT value FROM meta_config WHERE key = 'comfort_time_reference_value')\n                    / COALESCE(cooling_rate, 1)\n                ),\n            '0') AS Wert,\n            COALESCE('<= 6 Stunden', '') AS Grenzwert\n        FROM cooling_rate\n        WHERE datetime(timestamp) >= datetime('now', 'localtime')\n        ORDER BY timestamp ASC\n        LIMIT 1\n    )\n\n    UNION ALL\n\n    SELECT *\n    FROM (\n        SELECT \n            'Verdichter-LZ letzte Stunde' AS Parameter,\n            COALESCE(printf('%.0f Minuten', runtime_minutes_1h), '0 Minuten') AS Wert,\n            COALESCE('n/a', '') AS Grenzwert\n        FROM system_snapshot\n        WHERE installation_id = ${anlage_id}\n          AND timestamp_mez <= datetime('now','localtime')\n        ORDER BY timestamp_mez DESC\n        LIMIT 1\n    )\n\n    UNION ALL\n\n    SELECT *\n    FROM (\n        SELECT \n            'Kompressorstarts letzte Stunde' AS Parameter,\n            COALESCE(compressor_starts_1h, 0) AS Wert,\n            COALESCE('<= 2', '') AS Grenzwert\n        FROM system_snapshot\n        WHERE installation_id = ${anlage_id}\n          AND timestamp_mez <= datetime('now','localtime')\n        ORDER BY timestamp_mez DESC\n        LIMIT 1\n    )\n\n    UNION ALL\n\n    SELECT *\n    FROM (\n        SELECT \n            'Warmwasser-Temp letzte Stunde' AS Parameter,\n            COALESCE(printf('%.1f °C', dhw_temp), '0 °C') AS Wert,\n            COALESCE('> 50 Grad', '') AS Grenzwert\n        FROM system_snapshot\n        WHERE installation_id = ${anlage_id}\n          AND timestamp_mez <= datetime('now','localtime')\n        ORDER BY timestamp_mez DESC\n        LIMIT 1\n    )\n\n    UNION ALL\n\n    SELECT *\n    FROM (\n        SELECT\n            COALESCE(char(8203), '') AS Parameter,\n            COALESCE(char(8203), '') AS Wert,\n            COALESCE(char(8203), '') AS Grenzwert\n        FROM pv_window\n        WHERE pv_kw > 2\n          AND datetime(timestamp) >= datetime('now', 'localtime')\n        ORDER BY pv_next_peak DESC\n        LIMIT 1\n    )\n\n    UNION ALL\n\n    SELECT *\n    FROM (\n        SELECT\n            COALESCE(char(8203), '') AS Parameter,\n            COALESCE(char(8203), '') AS Wert,\n            COALESCE(char(8203), '') AS Grenzwert\n        FROM pv_window\n        WHERE pv_kw > 2\n          AND datetime(timestamp) >= datetime('now', 'localtime')\n        ORDER BY pv_next_peak DESC\n        LIMIT 1\n    )\n\n)\n\nWHERE\n(\n    '${s_decision}' = 'EIN'\n    OR EXISTS (\n        SELECT 1\n        FROM decision_logic\n        WHERE action = 'STABLE'\n          AND strftime('%F %H:00:00', 'now', 'localtime', '+1 hour')\n              = strftime('%F %H:00:00', timestamp)\n    )\n)\n",
     "rawQueryText": "SELECT *\nFROM (\n\n    SELECT *\n    FROM (\n        SELECT \n            'automatische Anlagen-Steuerung' AS Parameter,\n            COALESCE(char(8203), '') AS Wert,\n            COALESCE(char(8203), '') AS Grenzwert\n        FROM system_snapshot\n        WHERE installation_id = ${anlage_id}\n          AND timestamp_mez <= datetime('now','localtime')\n        ORDER BY timestamp_mez DESC\n        LIMIT 1\n    )\n\n    UNION ALL\n\n    SELECT *\n    FROM (\n        SELECT \n            'ergänzende Informationen: ' AS Parameter,\n            COALESCE(char(8203), '') AS Wert,\n            COALESCE(char(8203), '') AS Grenzwert\n        FROM system_snapshot\n        WHERE installation_id = ${anlage_id}\n          AND timestamp_mez <= datetime('now','localtime')\n        ORDER BY timestamp_mez DESC\n        LIMIT 1\n    )\n\n    UNION ALL\n\n    SELECT *\n    FROM (\n        SELECT\n            'Komfortzeit' AS Parameter,\n            COALESCE(\n                printf('%.1f',\n                    (SELECT value FROM meta_config WHERE key = 'temp_verlust_gebaeude')\n                    * (SELECT value FROM meta_config WHERE key = 'comfort_time_reference_value')\n                    / COALESCE(cooling_rate, 1)\n                ),\n            '0') AS Wert,\n            COALESCE('<= 6 Stunden', '') AS Grenzwert\n        FROM cooling_rate\n        WHERE datetime(timestamp) >= datetime('now', 'localtime')\n        ORDER BY timestamp ASC\n        LIMIT 1\n    )\n\n    UNION ALL\n\n    SELECT *\n    FROM (\n        SELECT \n            'Verdichter-LZ letzte Stunde' AS Parameter,\n            COALESCE(printf('%.0f Minuten', runtime_minutes_1h), '0 Minuten') AS Wert,\n            COALESCE('n/a', '') AS Grenzwert\n        FROM system_snapshot\n        WHERE installation_id = ${anlage_id}\n          AND timestamp_mez <= datetime('now','localtime')\n        ORDER BY timestamp_mez DESC\n        LIMIT 1\n    )\n\n    UNION ALL\n\n    SELECT *\n    FROM (\n        SELECT \n            'Kompressorstarts letzte Stunde' AS Parameter,\n            COALESCE(compressor_starts_1h, 0) AS Wert,\n            COALESCE('<= 2', '') AS Grenzwert\n        FROM system_snapshot\n        WHERE installation_id = ${anlage_id}\n          AND timestamp_mez <= datetime('now','localtime')\n        ORDER BY timestamp_mez DESC\n        LIMIT 1\n    )\n\n    UNION ALL\n\n    SELECT *\n    FROM (\n        SELECT \n            'Warmwasser-Temp letzte Stunde' AS Parameter,\n            COALESCE(printf('%.1f °C', dhw_temp), '0 °C') AS Wert,\n            COALESCE('> 50 Grad', '') AS Grenzwert\n        FROM system_snapshot\n        WHERE installation_id = ${anlage_id}\n          AND timestamp_mez <= datetime('now','localtime')\n        ORDER BY timestamp_mez DESC\n        LIMIT 1\n    )\n\n    UNION ALL\n\n    SELECT *\n    FROM (\n        SELECT\n            COALESCE(char(8203), '') AS Parameter,\n            COALESCE(char(8203), '') AS Wert,\n            COALESCE(char(8203), '') AS Grenzwert\n        FROM pv_window\n        WHERE pv_kw > 2\n          AND datetime(timestamp) >= datetime('now', 'localtime')\n        ORDER BY pv_next_peak DESC\n        LIMIT 1\n    )\n\n    UNION ALL\n\n    SELECT *\n    FROM (\n        SELECT\n            COALESCE(char(8203), '') AS Parameter,\n            COALESCE(char(8203), '') AS Wert,\n            COALESCE(char(8203), '') AS Grenzwert\n        FROM pv_window\n        WHERE pv_kw > 2\n          AND datetime(timestamp) >= datetime('now', 'localtime')\n        ORDER BY pv_next_peak DESC\n        LIMIT 1\n    )\n\n)\n\nWHERE\n(\n    '${s_decision}' = 'EIN'\n    OR EXISTS (\n        SELECT 1\n        FROM decision_logic\n        WHERE action = 'STABLE'\n          AND strftime('%F %H:00:00', 'now', 'localtime', '+1 hour')\n              = strftime('%F %H:00:00', timestamp)\n    )\n)\n",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Temperaturverlauf & Komfortzeit-Verlauf mit PV-Fenster",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "queryText": "SELECT \n  CAST(strftime('%s', timestamp, 'utc') AS INTEGER) AS time,\n  coalesce(cast(replace(temp_now,',', '.') as REAL), 0) * 1.0 as Außentemperatur\nFROM weather_forecast\nwhere strftime('%F %H:00:00', timestamp) between datetime(1776586522287/1000, 'unixepoch', 'localtime') \n      and datetime(1776759322287/1000, 'unixepoch', 'localtime')\nORDER BY time asc\n\n",
     "rawQueryText": "SELECT \n  CAST(strftime('%s', timestamp, 'utc') AS INTEGER) AS time,\n  coalesce(cast(replace(temp_now,',', '.') as REAL), 0) * 1.0 as Außentemperatur\nFROM weather_forecast\nwhere strftime('%F %H:00:00', timestamp) between datetime($__from/1000, 'unixepoch', 'localtime') \n      and datetime($__to/1000, 'unixepoch', 'localtime')\nORDER BY time asc\n\n",
     "rawSql": "SELECT timestamp as time, temp_now as value FROM weather_forecast ORDER BY timestamp;",
     "timeColumns": [
      "time",
      "ts"
     ]
    },
    {
     "queryText": "SELECT\n   cast(strftime('%s', timestamp, 'utc') as integer) as time,\n\n   ((select value from meta_config where key = 'temp_verlust_gebaeude') * (select value from meta_config where key = 'comfort_time_reference_value'))\n   /\n  cooling_rate\n  as 'Komfortzeit (h)'\n\n   from cooling_rate\n\nwhere strftime('%F %H:00:00', timestamp) between datetime(1776586522287/1000, 'unixepoch', 'localtime') \n      and datetime(1776759322287/1000, 'unixepoch', 'localtime')",
     "rawQueryText": "SELECT\n   cast(strftime('%s', timestamp, 'utc') as integer) as time,\n\n   ((select value from meta_config where key = 'temp_verlust_gebaeude') * (select value from meta_config where key = 'comfort_time_reference_value'))\n   /\n  cooling_rate\n  as 'Komfortzeit (h)'\n\n   from cooling_rate\n\nwhere strftime('%F %H:00:00', timestamp) between datetime($__from/1000, 'unixepoch', 'localtime') \n      and datetime($__to/1000, 'unixepoch', 'localtime')",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Verdichterlaufzeit (min/h) ab jetzt",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 58 },
   "targets": [
    {
     "queryText": "SELECT\n  CAST(strftime('%s', timestamp_mez, 'utc') AS INTEGER) AS time,\n  strftime('%H:00', timestamp_mez) as Achse, \n  runtime_minutes_1h AS 'Verdichterlaufzeit pro Stunde'\nFROM system_snapshot\nwhere installation_id = ${anlage_id} \nORDER BY timestamp_mez desc \nLimit 12\n",
     "rawQueryText": "SELECT\n  CAST(strftime('%s', timestamp_mez, 'utc') AS INTEGER) AS time,\n  strftime('%H:00', timestamp_mez) as Achse, \n  runtime_minutes_1h AS 'Verdichterlaufzeit pro Stunde'\nFROM system_snapshot\nwhere installation_id = ${anlage_id} \nORDER BY timestamp_mez desc \nLimit 12\n",
     "rawSql": "SELECT strftime('%Y-%m-%d %H:00:00', timestamp) as time, SUM(runtime_seconds)/3600.0 as value FROM heatpump_runtime GROUP BY time ORDER BY time;",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Kompressorstarts je  Stunde ab jetzt",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 58 },
   "targets": [
    {
     "queryText": "SELECT\n  CAST(strftime('%s', timestamp_mez, 'utc') AS INTEGER) AS time,\n  strftime('%H:00', timestamp_mez) as Achse, \n  compressor_starts_1h AS 'Kompressorstarts pro Stunde'\nFROM system_snapshot\nwhere installation_id = ${anlage_id} \n    \nORDER BY timestamp_mez desc \nLimit 12\n",
     "rawQueryText": "SELECT\n  CAST(strftime('%s', timestamp_mez, 'utc') AS INTEGER) AS time,\n  strftime('%H:00', timestamp_mez) as Achse, \n  compressor_starts_1h AS 'Kompressorstarts pro Stunde'\nFROM system_snapshot\nwhere installation_id = ${anlage_id} \n    \nORDER BY timestamp_mez desc \nLimit 12\n",
     "rawSql": "SELECT strftime('%Y-%m-%d %H:00:00', timestamp) as time, SUM(runtime_seconds)/3600.0 as value FROM heatpump_runtime GROUP BY time ORDER BY time;",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Pufferspeicher-Temperatur am Ende der Stunde",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 58 },
   "targets": [
    {
     "queryText": "SELECT\n  CAST(strftime('%s', timestamp_mez, 'utc') AS INTEGER) AS time,\n  strftime('%H:00', timestamp_mez) as Achse, \n  buffer_temp AS 'Pufferspeicher-Temperatur'\nFROM system_snapshot\nwhere installation_id = ${anlage_id} \n    \nORDER BY timestamp_mez desc \nLimit 12\n\n",
     "rawQueryText": "SELECT\n  CAST(strftime('%s', timestamp_mez, 'utc') AS INTEGER) AS time,\n  strftime('%H:00', timestamp_mez) as Achse, \n  buffer_temp AS 'Pufferspeicher-Temperatur'\nFROM system_snapshot\nwhere installation_id = ${anlage_id} \n    \nORDER BY timestamp_mez desc \nLimit 12\n\n",
     "rawSql": "SELECT strftime('%Y-%m-%d %H:00:00', timestamp) as time, SUM(runtime_seconds)/3600.0 as value FROM heatpump_runtime GROUP BY time ORDER BY time;",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Warmwasser-Temperatur am Ende der Stunde",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 58 },
   "targets": [
    {
     "queryText": "SELECT\n  CAST(strftime('%s', timestamp_mez, 'utc') AS INTEGER) AS time,\n  strftime('%H:00', timestamp_mez) as Achse, \n  dhw_temp AS 'Warmwasser-Temperatur'\nFROM system_snapshot\nwhere installation_id = ${anlage_id} \n    \nORDER BY timestamp_mez desc \nLimit 12\n",
     "rawQueryText": "SELECT\n  CAST(strftime('%s', timestamp_mez, 'utc') AS INTEGER) AS time,\n  strftime('%H:00', timestamp_mez) as Achse, \n  dhw_temp AS 'Warmwasser-Temperatur'\nFROM system_snapshot\nwhere installation_id = ${anlage_id} \n    \nORDER BY timestamp_mez desc \nLimit 12\n",
     "rawSql": "SELECT strftime('%Y-%m-%d %H:00:00', timestamp) as time, SUM(runtime_seconds)/3600.0 as value FROM heatpump_runtime GROUP BY time ORDER BY time;",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  }
 ]
}